// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjzjA0tLmhwU4PsL-UgLg2IkhWoBqxhs',
    appId: '1:68625357780:web:a6a2d1d5b7ddc976c2d441',
    messagingSenderId: '68625357780',
    projectId: 'whatsapp-fc69b',
    authDomain: 'whatsapp-fc69b.firebaseapp.com',
    storageBucket: 'whatsapp-fc69b.appspot.com',
    measurementId: 'G-WLCZYDFC9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZd5hBOS75KSOMyIEhmNexB7NG5EZiSlM',
    appId: '1:68625357780:android:b5abf9ded88b24abc2d441',
    messagingSenderId: '68625357780',
    projectId: 'whatsapp-fc69b',
    storageBucket: 'whatsapp-fc69b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-GPviNH2dE8DYeYVfxYZhLdBdkxAp8c',
    appId: '1:68625357780:ios:6ac2ad4abd4a3fefc2d441',
    messagingSenderId: '68625357780',
    projectId: 'whatsapp-fc69b',
    storageBucket: 'whatsapp-fc69b.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
